.Dd March 11, 2013
.Dt NVDSYNC 1
.Os
.Sh NAME
.Nm nvdsync
.Nd fetch NIST's NVD data and cross-reference it with Jira
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Sh DESCRIPTION
The
.Nm
utility wraps the
.Xr nvdXjira 1
tool to provide a simple script suitable to be run from a cronjob in order
to fetch NIST's National Vulnerability Database and then cross-reference
that database with a Jira instance.
.Sh OPTIONS
.Nm
supports the following options:
.Bl -tag -width p_
.It Fl h
Print a short usage statement and exit.
.It Fl v
Be verbose.
Can be specified multiple times.
.El
.Sh ENVIRONMENT
.Nm
honors the following environment variables:
.Bl -tag -width NVDXJIRA_FLAGS_
.It WGET_FLAGS
Flags to pass to
.Xr wget 1 ,
if any.
.It NVDXJIRA_FLAGS
Flags to pass to
.Xr nvdXjira 1 ,
if any.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr nvdXjira 1 ,
.Xr yvc 1
.Sh HISTORY
.Nm
was originally written by
.An Jan Schaumann
.Aq jschauma@twitter.com
in May 2013.
